### ISSUE TITLE
More live badge support

### ISSUE THREAD

**Issue by amio** [amio/badgen-service#2]
There are two kinds of live badge in badgen service:
1. **Has "official" badge service with same style**, like travis, circleci.
  badgen service will respond a 302 redirect to the official address, theoretically that should be the fastest badge service.
2. **Has an api for generating badge**, like npm version, npm downloads.
  badgen service will respond ~~a 302 redirect to resolved static badge url~~(In favor of Now CDN, no more perf tricks 🎉💪) the badge, depends on api response, and cache that response data for 60 seconds.

If you would like to propose a badge, please post it here, the api service or the official badge url schema.

There's a long list on shields.io to implement one by one, hope that won't take too long :P

**Comment by simov** [comment]
:wave: аре you interested in having Chrome Web Store badges like:

```
- https://img.shields.io/chrome-web-store/v/nimelepbpejjlbmoobocpfnjhihnpked.svg
- https://img.shields.io/chrome-web-store/users/nimelepbpejjlbmoobocpfnjhihnpked.svg
- https://img.shields.io/chrome-web-store/price/nimelepbpejjlbmoobocpfnjhihnpked.svg
- https://img.shields.io/chrome-web-store/rating/nimelepbpejjlbmoobocpfnjhihnpked.svg
- https://img.shields.io/chrome-web-store/stars/nimelepbpejjlbmoobocpfnjhihnpked.svg
- https://img.shields.io/chrome-web-store/rating-count/nimelepbpejjlbmoobocpfnjhihnpked.svg
```

A few months ago I published my own module for scraping the extension's data from Chrome Web Store called: [chrome-webstore](https://github.com/simov/chrome-webstore). The idea is that the dependency used in shields.io for this purpose is a bit heavy on RAM and slow on execution time. It uses the `request` module under the hood which is pretty bloated as you may know, and also it constructs an in-memory DOM with `cheerio` just to scrape the data off of the page (which is slow).

My module on the other hand have only 2 dependencies (deep) and I'm scraping the data off of the Chrome Web Store using Regular Expressions, which is way faster.

I'm yet to open a PR in shields.io and propose my module there as well, but since your service came recently I can add it here if you want.

**Comment by amio** [comment]
Would love to have a chrome-web-store badge! 💪

**Comment by amio** [comment]
Live badge propose goes to standalone issues
